
import React, { useState } from 'react';
import { Icons } from '../constants';

interface IntelligenceBlockProps {
  answer: string;
  isThinking: boolean;
  confidence: number;
  onShowSources: () => void;
  hasSources: boolean;
}

const IntelligenceBlock: React.FC<IntelligenceBlockProps> = ({ 
  answer, 
  isThinking, 
  confidence, 
  onShowSources,
  hasSources
}) => {
  if (isThinking) {
    return (
      <div className="w-full bg-blue-600/5 border border-blue-500/20 rounded-3xl p-6 mb-8 animate-pulse">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-blue-600 p-2 rounded-xl">
            <Icons.Brain />
          </div>
          <div className="h-4 w-32 bg-gray-700 rounded"></div>
        </div>
        <div className="space-y-3">
          <div className="h-3 w-full bg-gray-800 rounded"></div>
          <div className="h-3 w-[90%] bg-gray-800 rounded"></div>
          <div className="h-3 w-[70%] bg-gray-800 rounded"></div>
        </div>
      </div>
    );
  }

  if (!answer) return null;

  return (
    <div className="w-full relative overflow-hidden bg-gradient-to-br from-blue-600/10 via-gray-900 to-gray-900 border border-blue-500/30 rounded-3xl p-8 mb-10 shadow-2xl shadow-blue-500/5 group">
      <div className="absolute top-0 right-0 p-4 opacity-20 group-hover:opacity-40 transition-opacity">
         <Icons.Shield />
      </div>

      <div className="flex items-center gap-4 mb-6">
        <div className="bg-blue-600 p-2.5 rounded-2xl shadow-xl shadow-blue-500/40">
          <Icons.Brain />
        </div>
        <div>
          <h3 className="text-sm font-bold text-blue-400 uppercase tracking-widest">Cognitive Synthesis</h3>
          <p className="text-[10px] text-gray-500 font-mono">CONFIDENCE: {(confidence * 100).toFixed(1)}%</p>
        </div>
      </div>

      <div className="text-xl md:text-2xl font-medium text-gray-100 leading-relaxed mb-8">
        {answer}
      </div>

      <div className="flex items-center justify-between pt-6 border-t border-gray-800/50">
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div>
          Generated by Gemini 3 Flash v1.0
        </div>
        
        {hasSources && (
          <button 
            onClick={onShowSources}
            className="text-xs font-bold text-blue-400 hover:text-blue-300 transition-colors flex items-center gap-1 uppercase tracking-tighter"
          >
            Review Evidence Sources
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="m6 9 6 6 6-6"/></svg>
          </button>
        )}
      </div>
    </div>
  );
};

export default IntelligenceBlock;
